{% set name = "celerite" %}
{% set version = "0.3.1" %}
{% set sha256 = "427b36326d3c3d31d8f37c912afb6d1c23263b90ae24b3983705f9dbb98c64e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - python setup.py install --single-version-externally-managed --record record.txt  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pybind11
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - setuptools  # [win]
    - vs2015_runtime  # [win]

test:
  imports:
    - celerite

about:
  home: http://github.com/dfm/celerite
  license: MIT
  license_file: LICENSE
  summary: 'Scalable 1D Gaussian Processes in C++ and Python'
  doc_url: http://celerite.readthedocs.io/
  dev_url: https://github.com/dfm/celerite

extra:
  recipe-maintainers:
    - dfm
