travis:
  secure:
    BINSTAR_TOKEN: UI9+UlfokkqkQzAlx0p5RE2M1fs1wMjLJXwhzzZUFdrP97Xws87D3zoJkq6JyXowILEymT5LMsEOK23+3KhKvbMGHuFeoMN4g57yBYkP080y6yCj/a8GSd87sO5l+cIwyuCuurfXLzTmekVBDCKSrAUM+PKI3qmqvxwHhI+x2VzDn8zNtbfMYwQtKCnXWLkQihCiBsqdtCJOWAphWVaj1QiQYGVxIEA11FM6NjftJcJxEAi0AQP3AmeW6R28dDzyuLN9Ir5i1ERDv9c52pqCCmOSk2MLeTJxOElHbquf/PFibwI8g9guD4pTK9AmzaRxS8MNWD7Dw05GtpFqKlUgpCpDJCuJHY+sxDSx8S6v7jMlq1zzu/2xWWX/vydrOkHm2TPAF5aD4RDnEs+skAKlrZ/nVtdbMiR6JpStyjOMvs5y+tqqk7cWR9GaGk+McELbxqVzTo7cY6HNzEpp1QwkGbhKNiBbE5IaWoYoqjWB/x+G+gXywvd7W2neIBpovTqqFzPD0TckYuSkh/Vu35bHRUd1+AI2oaWCHoifmUYwyCzjE6GlOWok6WAUCPEHmiuZobZLJeNSFGP25IEFRQFI86erPlqxs+GuRWmGogq7guaYow9MKYBHbTA7WPwOuM3HXjOlRm7RMS6MULw+V/xy0ErkOoEh/AtROWOcUlMMvEw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
